### ISSUE TITLE
Npm Install Fails

### ISSUE THREAD

**Issue by cristiandley** [kciter/react-barcode#3] opened 2016-05-10 15:56 UTC
Hi, im having a weird issue when installing this package.

I tested it on Windows/Ubuntu and i have the same issue and with two vesions of Node

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN mpfnq-mdd@1.0.0 No repository field.
npm ERR! Linux 4.2.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-barcode"
npm ERR! node v4.4.3
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.3.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cristiandley/proyectos/mdd/npm-debug.log
```

im missing something ?

**Comment by windgaucho** [comment] 2016-05-10 15:57
this has happened to me too!!

**Comment by kciter** [comment] 2016-05-10 16:19
Oops! I had fixed a hurry just now. `react-barcode` was version upgraded. Check it up please. 😢 Sorry.

**Comment by cristiandley** [comment] 2016-05-10 16:24
@kciter seems to be having other issue now

```
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-36-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/cristiandley/proyectos/mdd/node_modules/canvas
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN mpfnq-mdd@1.0.0 No repository field.
npm ERR! Linux 4.2.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-barcode"
npm ERR! node v4.4.3
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.3.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cristiandley/proyectos/mdd/npm-debug.log
```

**Comment by windgaucho** [comment] 2016-05-10 16:25
@kciter Thank you for your fast response!! but I have the same problem

**Comment by kciter** [comment] 2016-05-10 16:36
`Make sure you have the latest version of node.js and npm installed`
May I ask your node.js and npm version?

**Comment by cristiandley** [comment] 2016-05-10 16:37
Im actually using:

- node v4.4.3
- npm v3.8.7

both linux and windows

**Comment by lindell** [comment] 2016-05-10 16:52
Try installing the dependencies of https://github.com/Automattic/node-canvas

**Comment by kciter** [comment] 2016-05-10 17:06
`canvas` already depend on `JsBarcode`. I think that [this page](https://github.com/Automattic/node-canvas/wiki/_pages) may be able to help.

**Comment by lindell** [comment] 2016-05-10 17:32
@kciter You should probably allow people to install with bower as well. The problem is that the canvas library is not required to make it work on the client side. But I can't remove it since the server side (nodejs) version of JsBarcode depends on it.

**Comment by windgaucho** [comment] 2016-05-10 20:42
I successfully install this library in mi macbook using the @lindell approach (https://github.com/Automattic/node-canvas#installation). I installed canvas an all your dependencies and then install reac-barcode. The npm install works now, later (tomorrow at work) I will try in Windows and let you know, thanks @lindell, @kciter and @cristiandley.

**Comment by windgaucho** [comment] 2016-05-12 13:18
I can't install on windows 10

**Comment by lindell** [comment] 2016-07-26 10:15
The `node-canvas` dependency is now gone (moved to devDependecies) from `JsBarcode`. This mean that you should be able to install `react-barcode` without this problem as a result.

**Comment by kciter** [comment] 2016-07-27 03:06
Hi guys.
I update to dependency version from `JsBarcode` version 3.3.16.
Check it out please.

**Comment by lindell** [comment] 2016-08-02 10:41
Could @cristiandley or @windgaucho please confirm that this solves the issue?

It should be fixed and I can install on Windows without the necessary `node-canvas` dependencies installed. 
![image](https://cloud.githubusercontent.com/assets/284868/17325893/59ac5998-58ae-11e6-8c36-220e5b18ed4f.png)

**Comment by kciter** [comment] 2016-08-11 09:15
Is it solved? 😮

**Comment by lindell** [comment] 2016-08-11 09:16
It's been more than two weeks since it was fixed. I think it's safe to close the issue.

**Closed** 2016-08-11 09:17 UTC
